apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Applications
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: default
    name: in-cluster
  source:
    path: apps
    repoURL: https://github.com/spencerr/poc-argo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true