{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "services-bar-ingress.fullname" . }}
  labels:
    {{- include "services-bar.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.hostName }}
    http:
      paths:
      - path: /{{ .Values.ingress.hostPrefix }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "services-bar.fullname" . }}
            port:
              name: http
{{ end }}