apiVersion: v1
kind: Service
metadata:
  name: {{ include "services-foo.fullname" . }}
  labels:
    {{- include "services-foo.labels" . | nindent 4 }}
{{- if .Values.bridge-to-kubernetes.enabled }}
  annotations:
    routing.visualstudio.io/route-on-header=kubernetes-route-as: {{ .Values.bridge-to-kubernetes.route-as | quote }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "services-foo.selectorLabels" . | nindent 4 }}