name: Alpha Deployment

on:
  workflow_dispatch:
    inputs:
      image-tag:
        type: string
        required: true
jobs:
  preview-promotion:
    runs-on: ubuntu-latest
    steps:
    - name: Git - Checkout Manifest Repository
      uses: actions/checkout@v3

    - name: Deployment - Update Alpha Image
      working-directory: apps/b2k-pr-environment/services-foo/alpha
      run: |
        yq -i '.image.tag = "${{ inputs.image-tag }}"' values.yaml
    
    - name: Deployment - Commit Alpha Manifest
      run: |
        git config user.name "promote-action"
        git config user.email "<>"
        git commit -am "Promote ${{ inputs.image-tag }} to Alpha"
        git push

    - name: Argo - Setup
      run: |
        curl --insecure -sSL -o /usr/local/bin/argocd https://${{ secrets.ARGOCD_SERVER }}/download/argocd-linux-amd64
        chmod +x /usr/local/bin/argocd

    - name: Argo - Login
      run: |
        argocd login ${{ secrets.ARGOCD_SERVER }} \
          --insecure \
          --username ${{ secrets.ARGOCD_USERNAME }} \
          --password ${{ secrets.ARGOCD_PASSWORD }}

    - name: Argo - Sync
      run: |
        argocd app sync alpha-services-foo

    - name: Argo - Wait
      run: |
        argocd app wait alpha-services-foo
