name: Alpha Deployment

on:
  workflow_dispatch:
    inputs:
      image-tag:
        type: string
        required: true
      commit:
        type: boolean
        default: true
jobs:
  preview-promotion:
    runs-on: ubuntu-latest
    steps:
    - name: Git - Checkout Manifest Repository
      uses: actions/checkout@v3

    - name: Deployment - Retrieve Alpha Image
      id: current-tag
      if: inputs.commit
      working-directory: apps/b2k-pr-environment/services-foo/alpha
      run: |
        IMAGE_TAG=$(yq '.image.tag' values.yaml)
        echo "$IMAGE_TAG"
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Deployment - Update Alpha Image
      if: inputs.commit && steps.current-tag.outputs.IMAGE_TAG != inputs.image-tag
      working-directory: apps/b2k-pr-environment/services-foo/alpha
      run: |
        yq -i '.image.tag = "${{ inputs.image-tag }}"' values.yaml
    
    - name: Deployment - Commit Alpha Manifest
      if: inputs.commit && steps.current-tag.outputs.IMAGE_TAG != inputs.image-tag
      run: |
        git config user.name "promote-bot"
        git config user.email "<>"
        git commit -am "Promote ${{ inputs.image-tag }} to Alpha"
        git push

    - name: Argo - Setup
      run: |
        curl --insecure -sSL -o /usr/local/bin/argocd https://${{ secrets.ARGOCD_SERVER }}/download/argocd-linux-amd64
        chmod +x /usr/local/bin/argocd

    - name: Argo - Login
      run: |
        argocd login ${{ secrets.ARGOCD_SERVER }} \
          --insecure \
          --username ${{ secrets.ARGOCD_USERNAME }} \
          --password ${{ secrets.ARGOCD_PASSWORD }}

    - name: Argo - Set Image Tag
      if: !inputs.commit
      run: |
        argocd app set alpha-services-foo -p image.tag=${{ inputs.image-tag }}

    - name: Argo - Sync
      run: |
        argocd app sync alpha-services-foo

    - name: Argo - Wait
      run: |
        argocd app wait alpha-services-foo
