name: Beta Promotion

on:
  workflow_dispatch:
    inputs:
      service-name:
        type: string
        required: true
jobs:
  preview-promotion:
    runs-on: ubuntu-latest
    steps:
    - name: Git - Checkout Manifest Repository
      uses: actions/checkout@v3

    - name: Promote - Retrieve Alpha Image
      working-directory: apps/b2k-pr-environment/services-foo/alpha
      run: |
        IMAGE_SHA=$(yq '.image.tag' values.yaml)
        echo "$IMAGE_SHA"
        echo "IMAGE_SHA=$IMAGE_SHA" >> $GITHUB_ENV

    - name: Promote - Update Beta Image
      working-directory: apps/b2k-pr-environment/services-foo/beta
      run: |
        yq -i '.image.tag = "${{ env.IMAGE_SHA }}"' values.yaml
    
    - name: Promote - Commit Beta Manifest
      run: |
        git config user.name "promote-action"
        git config user.email "<>"
        git commit -am "Promote $IMAGE_SHA to Beta"
        git push

    - name: Argo - Setup
      run: |
        curl --insecure -sSL -o /usr/local/bin/argocd https://${{ secrets.ARGOCD_SERVER }}/download/argocd-linux-amd64
        chmod +x /usr/local/bin/argocd

    - name: Argo - Login
      run: |
        argocd login ${{ secrets.ARGOCD_SERVER }} \
          --insecure \
          --username ${{ secrets.ARGOCD_USERNAME }} \
          --password ${{ secrets.ARGOCD_PASSWORD }}

    - name: Argo - Sync
      run: |
        argocd app sync beta-services-foo

    - name: Argo - Wait
      run: |
        argocd app wait beta-services-foo
